apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      tier: back-end
  template: # Pod template (pod-definition.yml)
    metadata:
      name: myapp-pod
      labels: # Dictionary
        app: myapp
        tier: back-end
    spec: # Specification
      containers: # List of dictionaries
        - name: nginx-container
          image: nginx:1-alpine # Docker Hub
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
