apiVersion: v1
kind: Service
metadata:
  name: myapp-node-port-service
spec:
  type: NodePort
  selector:
    app: myapp
    tier: back-end
  ports:
    - nodePort: 30008 # Automatically assigned if it's not specified (30000 - 32767)
      port: 80
      targetPort: 80 # targetPort = port if it's not specified
