apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: # Dictionary
    name: myapp
    tier: back-end
spec: # Specification
  containers: # List of dictionaries
    - name: nginx-container
      image: nginx # Docker Hub
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
