apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication-controller
  labels:
    app: myapp
    tier: back-end
spec:
  replicas: 3
  selector: # Optional
    app: myapp
  template: # Pod template (pod-definition.yml)
    metadata:
      name: myapp-pod
      labels: # Dictionary
        app: myapp
        tier: back-end
    spec: # Specification
      containers: # List of dictionaries
        - name: nginx-container
          image: nginx # Docker Hub
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
